/*
 * Copyright (C) 2024-2026 David C. Manuelda (StormBytePP)
 *
 * This file is part of StormByte-Multimedia.
 *
 * StormByte-Multimedia original source is dual-licensed:
 *
 * 1. GNU Lesser General Public License v3.0 (or later)
 *    You may redistribute and/or modify this file under the terms of the
 *    GNU Lesser General Public License as published by the Free Software
 *    Foundation, either version 3 of the License, or (at your option)
 *    any later version.
 *
 * 2. Commercial license
 *    Alternatively, this file may be used under the terms of a commercial
 *    license agreement with the copyright holder
 *    (David C. Manuelda <StormByte@gmail.com>).
 *
 * Both licenses apply only to original StormByte-Multimedia source in this
 * file. Third-party components — including FFmpeg and embedded trained data —
 * remain under their own licenses and are not covered by the commercial grant.
 *
 * Neither license grants any patent rights. Any patent licenses required
 * to use this software or third-party components must be obtained separately
 * from the patent holders.
 *
 * StormByte-Multimedia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 3 along with StormByte-Multimedia. If not, see
 * <https://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-StormByte-Commercial
 */

#include <StormByte/multimedia/tables/container/table.hxx>

using namespace StormByte::Multimedia::Tables::Container;

namespace {
	constexpr ContainerDef table[] = {
		{ "3DO STR",			"3DO STR",					{ "3dostr" },				{ "str" } },
		{ "3GPP",				"3GPP",						{ "3gp" },					{ "3gp", "3gpp" } },
		{ "3GPP2",				"3GPP2",					{ "3g2" },					{ "3g2", "3gp2" } },
		{ "4X Movie",			"4X Movie",					{ "4xm" },					{ "4xm" } },
		{ "A-law",				"Raw A-law PCM",			{ "alaw" },					{ "al" } },
		{ "AA",					"Audible AA",				{ "aa" },					{ "aa" } },
		{ "AAC",				"Raw ADTS AAC",				{ "aac" },					{ "aac", "adts" } },
		{ "AAX",				"Audible AAX",				{ "aax" },					{ "aax" } },
		{ "AC-3",				"Raw AC-3",					{ "ac3" },					{ "ac3" } },
		{ "ACE",				"tri-Ace ACE",				{ "ace" },					{ "ace" } },
		{ "ACM",				"Interplay ACM",			{ "acm" },					{ "acm" } },
		{ "ACT",				"ACT Voice",				{ "act" },					{ "act" } },
		{ "ADF",				"Artworx ADF",				{ "adf" },					{ "adf" } },
		{ "ADP",				"ADP",						{ "adp" },					{ "adp", "adp2" } },
		{ "ADS",				"Sony ADS",					{ "ads" },					{ "ads", "ss2" } },
		{ "ADX",				"CRI ADX",					{ "adx" },					{ "adx" } },
		{ "AEA",				"MD STUDIO audio",			{ "aea" },					{ "aea" } },
		{ "AFC",				"Nintendo AFC",				{ "afc" },					{ "afc" } },
		{ "AIFF",				"Audio IFF",				{ "aiff" },					{ "aif", "aiff", "afc", "aifc" } },
		{ "AIX",				"CRI AIX",					{ "aix" },					{ "aix" } },
		{ "ALAC",				"Raw Apple Lossless",		{ "alac" },					{ "alac" } },
		{ "AMR",				"3GPP AMR",					{ "amr" },					{ "amr" } },
		{ "AMV",				"AMV",						{ "amv" },					{ "amv" } },
		{ "ANM",				"Deluxe Paint Animation",	{ "anm" },					{ "anm" } },
		{ "APC",				"CRYO APC",					{ "apc" },					{ "apc" } },
		{ "APE",				"Monkey's Audio",			{ "ape" },					{ "ape", "apl", "mac" } },
		{ "APM",				"Ubisoft APM",				{ "apm" },					{ "apm" } },
		{ "APNG",				"Animated PNG",				{ "apng" },					{ "apng" } },
		{ "APTX",				"aptX",						{ "aptx" },					{ "aptx" } },
		{ "APTX HD",			"aptX HD",					{ "aptx_hd" },				{ "aptxhd" } },
		{ "AQTitle",			"AQTitle subtitles",		{ "aqtitle" },				{ "aqt" } },
		{ "ASF",				"Advanced Systems Format",	{ "asf", "asf_o" },			{ "asf", "wmv", "wma" } },
		{ "AST",				"Nintendo AST",				{ "ast" },					{ "ast" } },
		{ "AU",					"Sun AU",					{ "au" },					{ "au" } },
		{ "AVI",				"Audio Video Interleave",	{ "avi" },					{ "avi" } },
		{ "AVR",				"Audio Visual Research",	{ "avr" },					{ "avr" } },
		{ "AVS",				"Argonaut AVS",				{ "avs" },					{ "avs" } },
		{ "AVS2",				"Raw AVS2 video",			{ "avs2" },					{ "avs2", "avs3" } },
		{ "AVS3",				"Raw AVS3 video",			{ "avs3" },					{ "avs3" } },
		{ "Adobe Filmstrip",	"Adobe Filmstrip",			{ "filmstrip" },			{ "flm" } },
		{ "Argo ASF",			"Argonaut ASF",				{ "argo_asf" },				{ "asf" } },
		{ "Argo BRP",			"Argonaut BRP",				{ "argo_brp" },				{ "brp" } },
		{ "Argo CVG",			"Argonaut CVG",				{ "argo_cvg" },				{ "cvg" } },
		{ "BETHEX",				"Bethesda VID",				{ "bethsoftvid" },			{ "vid" } },
		{ "BFI",				"Brute Force & Ignorance",	{ "bfi" },					{ "bfi" } },
		{ "BFSTM",				"Nintendo BFSTM",			{ "bfstm" },				{ "bfstm", "bcstm" } },
		{ "BINK",				"RAD Bink",					{ "bink" },					{ "bik", "bk2" } },
		{ "BIT",				"G.729 BIT",				{ "bit" },					{ "bit" } },
		{ "BMV",				"Discworld II BMV",			{ "bmv" },					{ "bmv" } },
		{ "BOA",				"Black Oak Bytestream",		{ "boa" },					{ "boa" } },
		{ "BONK",				"Bonk audio",				{ "bonk" },					{ "bonk" } },
		{ "BRSTM",				"Nintendo BRSTM",			{ "brstm" },				{ "brstm" } },
		{ "C93",				"Interplay C93",			{ "c93" },					{ "c93" } },
		{ "CAF",				"Apple CAF",				{ "caf" },					{ "caf" } },
		{ "CDG",				"CD Graphics",				{ "cdg" },					{ "cdg" } },
		{ "CDXL",				"Commodore CDXL",			{ "cdxl" },					{ "cdxl", "xl" } },
		{ "CINE",				"Phantom Cine",				{ "cine" },					{ "cine" } },
		{ "Codec2",				"Codec2",					{ "codec2" },				{ "c2" } },
		{ "Codec2 raw",			"Codec2 raw",				{ "codec2raw" },			{ "c2" } },
		{ "DASH",				"MPEG-DASH",				{ "dash" },					{ "mpd" } },
		{ "D-Cinema audio",		"D-Cinema audio",			{ "daud" },					{ "302" } },
		{ "DCSTR",				"Sega DC STR",				{ "dcstr" },				{ "str" } },
		{ "DERF",				"Xilam DERF",				{ "derf" },					{ "derf" } },
		{ "DFA",				"Chronomaster DFA",			{ "dfa" },					{ "dfa" } },
		{ "DFPWM",				"DFPWM",					{ "dfpwm" },				{ "dfpwm" } },
		{ "DHAV",				"Xiaohua DHAV",				{ "dhav" },					{ "dav", "dhav" } },
		{ "Dirac",				"Raw Dirac",				{ "dirac" },				{ "drc", "vc2" } },
		{ "DNxHD",				"Raw DNxHD",				{ "dnxhd" },				{ "dnxhd", "dnxhr" } },
		{ "DSF",				"DSD Stream File",			{ "dsf" },					{ "dsf" } },
		{ "DSI CIN",			"Delphine CIN",				{ "dsicin" },				{ "cin" } },
		{ "DSS",				"Digital Speech Standard",	{ "dss" },					{ "dss" } },
		{ "DTS",				"Raw DTS",					{ "dts" },					{ "dts" } },
		{ "DTSHD",				"DTS-HD",					{ "dtshd" },				{ "dtshd" } },
		{ "DV",					"Digital Video",			{ "dv" },					{ "dv", "dif" } },
		{ "DXA",				"Feeble DXA",				{ "dxa" },					{ "dxa" } },
		{ "EA",					"Electronic Arts",			{ "ea" },					{ "ea" } },
		{ "EA cdata",			"Electronic Arts cdata",	{ "ea_cdata" },				{ "cdata" } },
		{ "E-AC-3",				"Raw E-AC-3",				{ "eac3" },					{ "eac3" } },
		{ "EPAF",				"Ensoniq Paris Audio",		{ "epaf" },					{ "epaf", "fap" } },
		{ "FFmpeg metadata",	"FFmpeg metadata",			{ "ffmetadata" },			{ "ffmeta" } },
		{ "FITS",				"Flexible Image Transport",	{ "fits" },					{ "fits" } },
		{ "FLAC",				"Free Lossless Audio Codec",{ "flac" },					{ "flac" } },
		{ "FLIC",				"Autodesk FLI/FLC",			{ "flic" },					{ "fli", "flc" } },
		{ "FLV",				"Flash Video",				{ "flv", "live_flv" },		{ "flv" } },
		{ "FRM",				"Megalink FRM",				{ "frm" },					{ "frm" } },
		{ "FSB",				"FMOD FSB",					{ "fsb" },					{ "fsb" } },
		{ "FWSE",				"Capcom FWSE",				{ "fwse" },					{ "fwse" } },
		{ "Film CPACK",			"Sega FILM / CPK",			{ "film_cpk" },				{ "cpk", "film" } },
		{ "G.722",				"Raw G.722",				{ "g722" },					{ "g722" } },
		{ "G.723.1",			"G.723.1",					{ "g723_1" },				{ "tco", "rco" } },
		{ "G.726",				"Raw G.726",				{ "g726" },					{ "g726" } },
		{ "G.726 LE",			"Raw G.726 little-endian",	{ "g726le" },				{ "g726" } },
		{ "G.729",				"G.729",					{ "g729" },					{ "g729" } },
		{ "GDV",				"Gremlin Digital Video",	{ "gdv" },					{ "gdv" } },
		{ "GENH",				"GENeRic Header",			{ "genh" },					{ "genh" } },
		{ "GIF",				"GIF",						{ "gif" },					{ "gif" } },
		{ "GSM",				"Raw GSM",					{ "gsm" },					{ "gsm" } },
		{ "GXF",				"SMPTE GXF",				{ "gxf" },					{ "gxf" } },
		{ "H.261",				"Raw H.261",				{ "h261" },					{ "h261" } },
		{ "H.263",				"Raw H.263",				{ "h263" },					{ "h263" } },
		{ "H.264",				"Raw H.264",				{ "h264" },					{ "h264", "264", "avc" } },
		{ "H.265",				"Raw H.265",				{ "hevc" },					{ "hevc", "h265", "265" } },
		{ "HCA",				"CRI HCA",					{ "hca" },					{ "hca" } },
		{ "HCOM",				"Macintosh HCOM",			{ "hcom" },					{ "hcom" } },
		{ "HLS",				"HTTP Live Streaming",		{ "hls" },					{ "m3u8", "m3u" } },
		{ "HNM",				"Cryo HNM4",				{ "hnm" },					{ "hnm" } },
		{ "ICO",				"Windows icon",				{ "ico" },					{ "ico" } },
		{ "IDCIN",				"id Quake II CIN",			{ "idcin" },				{ "cin" } },
		{ "IDF",				"iCEDraw",					{ "idf" },					{ "idf" } },
		{ "IFF",				"Amiga IFF",				{ "iff" },					{ "iff", "ilbm", "lbm" } },
		{ "IFV",				"IFV CCTV",					{ "ifv" },					{ "ifv" } },
		{ "iLBC",				"Internet Low Bitrate Codec",{ "ilbc" },				{ "lbc" } },
		{ "IMF",				"IMF",						{ "imf" },					{ "xml" } },
		{ "IPMovie",			"Interplay MVE",			{ "ipmovie" },				{ "mve" } },
		{ "IPU",				"Raw IPU",					{ "ipu" },					{ "ipu" } },
		{ "IRCAM",				"Berkeley IRCAM",			{ "ircam" },				{ "sf", "ircam" } },
		{ "ISS",				"Funcom ISS",				{ "iss" },					{ "iss" } },
		{ "IV8",				"IndigoVision 8000",		{ "iv8" },					{ "iv8" } },
		{ "IVF",				"On2 IVF",					{ "ivf" },					{ "ivf" } },
		{ "IVR",				"IndigoVision IVR",			{ "ivr" },					{ "ivr" } },
		{ "JACOsub",			"JACOsub",					{ "jacosub" },				{ "jss", "js" } },
		{ "JPEG XL Animated",	"Animated JPEG XL",			{ "jpegxl_anim" },			{ "jxl" } },
		{ "JV",					"Bitmap Brothers JV",		{ "jv" },					{ "jv" } },
		{ "KUX",				"KUX",						{ "kux" },					{ "kux" } },
		{ "KVAG",				"Simon & Schuster KVAG",	{ "kvag" },					{ "vag" } },
		{ "LAF",				"Limitless Audio Format",	{ "laf" },					{ "laf" } },
		{ "LMLM4",				"Raw LMLM4",				{ "lmlm4" },				{ "lmlm4" } },
		{ "LOAS",				"LOAS AAC",					{ "loas" },					{ "loas", "latm" } },
		{ "LRC",				"LRC lyrics",				{ "lrc" },					{ "lrc" } },
		{ "LVF",				"LVF",						{ "lvf" },					{ "lvf" } },
		{ "LXF",				"VR Natrix LXF",			{ "lxf" },					{ "lxf" } },
		{ "M4V",				"Raw MPEG-4 video",			{ "m4v" },					{ "m4v" } },
		{ "MCA",				"MCA audio",				{ "mca" },					{ "mca" } },
		{ "MCC",				"MacCaption",				{ "mcc" },					{ "mcc" } },
		{ "MGSTS",				"Metal Gear Solid TS",		{ "mgsts" },				{ "ts" } },
		{ "MJPEG",				"Raw MJPEG",				{ "mjpeg" },				{ "mjpg", "mjpeg" } },
		{ "MJPEG 2000",			"Raw MJPEG 2000",			{ "mjpeg_2000" },			{ "mjp2", "mj2" } },
		{ "MLP",				"Meridian Lossless Packing",{ "mlp" },					{ "mlp" } },
		{ "MLV",				"Magic Lantern Video",		{ "mlv" },					{ "mlv" } },
		{ "MM",					"American Laser Games MM",	{ "mm" },					{ "mm" } },
		{ "MMF",				"Yamaha SMAF",				{ "mmf" },					{ "mmf" } },
		{ "MODS",				"MODS",						{ "mods" },					{ "mods" } },
		{ "MOFLEX",				"MobiClip MOFLEX",			{ "moflex" },				{ "moflex" } },
		{ "MOV",				"QuickTime",				{ "mov" },					{ "mov", "qt" } },
		{ "MP2",				"MPEG audio layer 2",		{ "mp2" },					{ "mp2", "m2a", "mpa" } },
		{ "MP3",				"MPEG audio layer 3",		{ "mp3" },					{ "mp3" } },
		{ "MP4",				"MPEG-4 Part 14",			{ "mp4" },					{ "mp4", "m4a", "m4b", "m4r" } },
		{ "MPC",				"Musepack SV7",				{ "mpc" },					{ "mpc" } },
		{ "MPC8",				"Musepack SV8",				{ "mpc8" },					{ "mpc" } },
		{ "MPEG-1 System",		"MPEG-1 Systems",			{ "mpeg" },					{ "mpg", "mpeg", "vob" } },
		{ "MPEG-2 TS",			"MPEG-2 Transport Stream",	{ "mpegts", "mpegtsraw" },	{ "ts", "m2t", "m2ts", "mts" } },
		{ "MPEG video",			"Raw MPEG video",			{ "mpegvideo" },			{ "m1v", "m2v" } },
		{ "MPJPEG",				"Multipart JPEG",			{ "mpjpeg" },				{ "mjpg" } },
		{ "MPL2",				"MPL2 subtitles",			{ "mpl2" },					{ "mpl", "mpl2" } },
		{ "MPSUB",				"MPlayer subtitles",		{ "mpsub" },				{ "sub" } },
		{ "MSF",				"Sony PS3 MSF",				{ "msf" },					{ "msf" } },
		{ "MSP",				"Microsoft Paint",			{ "msp" },					{ "msp" } },
		{ "MTAF",				"Konami MTAF",				{ "mtaf" },					{ "mtaf" } },
		{ "MTV",				"MTV",						{ "mtv" },					{ "mtv" } },
		{ "MUSX",				"MUSX",						{ "musx" },					{ "musx" } },
		{ "MV",					"Silicon Graphics Movie",	{ "mv" },					{ "mv" } },
		{ "MVI",				"Motion Pixels MVI",		{ "mvi" },					{ "mvi" } },
		{ "MXF",				"Material eXchange Format",	{ "mxf" },					{ "mxf" } },
		{ "MXG",				"MxPEG clip",				{ "mxg" },					{ "mxg" } },
		{ "Matroska",			"Matroska",					{ "matroska" },				{ "mkv", "mka", "mks", "mk3d" } },
		{ "MicroDVD",			"MicroDVD subtitles",		{ "microdvd" },				{ "sub" } },
		{ "NC",					"NC camera",				{ "nc" },					{ "v" } },
		{ "NIST SPHERE",		"NIST SPHERE",				{ "nistsphere" },			{ "nist", "sph" } },
		{ "NSP",				"Computerized Speech Lab",	{ "nsp" },					{ "nsp" } },
		{ "NSV",				"Nullsoft Video",			{ "nsv" },					{ "nsv" } },
		{ "NUT",				"NUT",						{ "nut" },					{ "nut" } },
		{ "NUV",				"NuppelVideo",				{ "nuv" },					{ "nuv" } },
		{ "OBU",				"AV1 Open Bitstream Unit",	{ "obu" },					{ "obu", "av1" } },
		{ "Ogg",				"Ogg",						{ "ogg" },					{ "ogg", "ogv", "oga", "ogx" } },
		{ "OMA",				"Sony OpenMG",				{ "oma" },					{ "oma", "omg", "aa3" } },
		{ "Opus",				"Opus in Ogg",				{ "opus" },					{ "opus" } },
		{ "PAF",				"Amazing Studio PAF",		{ "paf" },					{ "paf" } },
		{ "PJS",				"PJS subtitles",			{ "pjs" },					{ "pjs" } },
		{ "PKM",				"PKM (ETC1)",				{ "pkm" },					{ "pkm" } },
		{ "PMP",				"Playstation Portable PMP",	{ "pmp" },					{ "pmp" } },
		{ "PPBnk",				"Pro Pinball series",		{ "pp_bnk" },				{ "bnk" } },
		{ "PVA",				"TechnoTrend PVA",			{ "pva" },					{ "pva" } },
		{ "PVF",				"PVF audio",				{ "pvf" },					{ "pvf" } },
		{ "QCP",				"QCP",						{ "qcp" },					{ "qcp" } },
		{ "QOA",				"Quite OK Audio",			{ "qoa" },					{ "qoa" } },
		{ "R3D",				"REDCODE R3D",				{ "r3d" },					{ "r3d" } },
		{ "RL2",				"RL2",						{ "rl2" },					{ "rl2" } },
		{ "RPL",				"Escape RPL",				{ "rpl" },					{ "rpl" } },
		{ "RSD",				"GameCube RSD",				{ "rsd" },					{ "rsd" } },
		{ "RSO",				"Lego Mindstorms RSO",		{ "rso" },					{ "rso" } },
		{ "RealMedia",			"RealMedia",				{ "rm" },					{ "rm", "ra", "ram" } },
		{ "RealText",			"RealText",					{ "realtext" },				{ "rt" } },
		{ "RedSpark",			"RedSpark",					{ "redspark" },				{ "rsd" } },
		{ "RKA",				"RK Audio",					{ "rka" },					{ "rka" } },
		{ "RoQ",				"id RoQ",					{ "roq" },					{ "roq" } },
		{ "S337M",				"SMPTE 337M",				{ "s337m" },				{ "pcm" } },
		{ "SAMI",				"SAMI subtitles",			{ "sami" },					{ "smi", "sami" } },
		{ "SBC",				"Bluetooth SBC",			{ "sbc" },					{ "sbc", "msbc" } },
		{ "SBG",				"SBaGen binaural",			{ "sbg" },					{ "sbg" } },
		{ "SCC",				"Scenarist Closed Captions",{ "scc" },					{ "scc" } },
		{ "SCD",				"Square Enix SCD",			{ "scd" },					{ "scd" } },
		{ "SDNS",				"Xbox SDNS",				{ "sdns" },					{ "sdns" } },
		{ "SDR2",				"SDR2",						{ "sdr2" },					{ "sdr2" } },
		{ "SDS",				"MIDI Sample Dump Standard",{ "sds" },					{ "sds" } },
		{ "SDX",				"Sample Dump eXchange",		{ "sdx" },					{ "sdx" } },
		{ "SER",				"SER",						{ "ser" },					{ "ser" } },
		{ "SGA",				"Digital Pictures SGA",		{ "sga" },					{ "sga" } },
		{ "SHN",				"Shorten",					{ "shn" },					{ "shn" } },
		{ "SIFF",				"Beam Software SIFF",		{ "siff" },					{ "vb", "son" } },
		{ "SIMX",				"Simbiosis IMX",			{ "simbiosis_imx" },		{ "imx" } },
		{ "SLN",				"Asterisk raw PCM",			{ "sln" },					{ "sln" } },
		{ "SMK",				"Smacker",					{ "smk" },					{ "smk" } },
		{ "SMUSH",				"LucasArts Smush",			{ "smush" },				{ "san", "anm" } },
		{ "SOL",				"Sierra SOL",				{ "sol" },					{ "sol" } },
		{ "SoX",				"SoX native",				{ "sox" },					{ "sox" } },
		{ "SPDIF",				"IEC 61937",				{ "spdif" },				{ "spdif" } },
		{ "SRT",				"SubRip",					{ "srt" },					{ "srt" } },
		{ "STL",				"Spruce subtitle",			{ "stl" },					{ "stl" } },
		{ "SUB",				"Raw DVD subtitle",			{ "dvbsub" },				{ "sub" } },
		{ "SUP",				"Raw PGS / SUP",			{ "sup" },					{ "sup" } },
		{ "SVAG",				"Konami SVAG",				{ "svag" },					{ "svag" } },
		{ "SVS",				"Square SVS",				{ "svs" },					{ "svs" } },
		{ "SWF",				"Shockwave Flash",			{ "swf" },					{ "swf" } },
		{ "Speex",				"Speex in Ogg",				{ "speex" },				{ "spx" } },
		{ "SubViewer",			"SubViewer v2",				{ "subviewer" },			{ "sub" } },
		{ "SubViewer 1",		"SubViewer v1",				{ "subviewer1" },			{ "sub" } },
		{ "TAK",				"Tom's lossless Audio",		{ "tak" },					{ "tak" } },
		{ "TED Captions",		"TED Talks captions",		{ "tedcaptions" },			{ "json" } },
		{ "THP",				"Nintendo THP",				{ "thp" },					{ "thp" } },
		{ "Theora",				"Theora in Ogg",			{ "theora" },				{ "ogv" } },
		{ "Tiertex SEQ",		"Tiertex SEQ",				{ "tiertexseq" },			{ "seq" } },
		{ "TMV",				"8088flex TMV",				{ "tmv" },					{ "tmv" } },
		{ "TrueHD",				"Raw TrueHD",				{ "truehd" },				{ "thd" } },
		{ "TTA",				"True Audio",				{ "tta" },					{ "tta" } },
		{ "TTY",				"Tele-typewriter",			{ "tty" },					{ "ans", "art", "asc", "diz", "ice", "nfo", "txt", "vt" } },
		{ "TXD",				"Renderware TXD",			{ "txd" },					{ "txd" } },
		{ "TiVo TY",			"TiVo TY",					{ "ty" },					{ "ty" } },
		{ "V210",				"V210",						{ "v210" },					{ "v210" } },
		{ "V210X",				"V210X",					{ "v210x" },				{ "yuv10" } },
		{ "VAG",				"Sony VAG",					{ "vag" },					{ "vag" } },
		{ "VC-1",				"Raw VC-1",					{ "vc1" },					{ "vc1" } },
		{ "VC-1 test",			"VC-1 test",				{ "vc1test" },				{ "rcv" } },
		{ "VMD",				"Sierra VMD",				{ "vmd" },					{ "vmd" } },
		{ "VOBSUB",				"VobSub",					{ "vobsub" },				{ "idx" } },
		{ "VOC",				"Creative Voice",			{ "voc" },					{ "voc" } },
		{ "VPK",				"Sony PS2 VPK",				{ "vpk" },					{ "vpk" } },
		{ "VPlayer",			"VPlayer subtitles",		{ "vplayer" },				{ "txt" } },
		{ "VQF",				"TwinVQ",					{ "vqf" },					{ "vqf" } },
		{ "Vividas",			"Vividas VIV",				{ "vividas" },				{ "viv" } },
		{ "Vivo",				"Vivo",						{ "vivo" },					{ "viv" } },
		{ "Vorbis",				"Vorbis in Ogg",			{ "vorbis" },				{ "oga" } },
		{ "W64",				"Sony Wave64",				{ "w64" },					{ "w64" } },
		{ "WADY",				"WADY",						{ "wady" },					{ "wady" } },
		{ "WAV",				"Waveform Audio",			{ "wav" },					{ "wav" } },
		{ "WAVARC",				"Waveform Archiver",		{ "wavarc" },				{ "wa" } },
		{ "WC3",				"Wing Commander III",		{ "wc3movie" },				{ "mve" } },
		{ "WebM",				"WebM",						{ "webm" },					{ "webm", "weba" } },
		{ "WebVTT",				"WebVTT",					{ "webvtt" },				{ "vtt" } },
		{ "Westwood AUD",		"Westwood AUD",				{ "wsaud" },				{ "aud" } },
		{ "Westwood VQA",		"Westwood VQA",				{ "wsvqa" },				{ "vqa" } },
		{ "WSD",				"Wideband Single-bit Data",	{ "wsd" },					{ "wsd" } },
		{ "WTV",				"Windows Television",		{ "wtv" },					{ "wtv" } },
		{ "WV",					"WavPack",					{ "wv" },					{ "wv" } },
		{ "WVE",				"Psion WVE",				{ "wve" },					{ "wve" } },
		{ "WebP",				"WebP",						{ "webp" },					{ "webp" } },
		{ "XA",					"Maxis XA",					{ "xa" },					{ "xa" } },
		{ "XBIN",				"eXtended BIN",				{ "xbin" },					{ "xbin" } },
		{ "XMD",				"Konami XMD",				{ "xmd" },					{ "xmd" } },
		{ "XMV",				"Xbox XMV",					{ "xmv" },					{ "xmv" } },
		{ "XVAG",				"Sony XVAG",				{ "xvag" },					{ "xvag" } },
		{ "XWMA",				"Xbox WMA",					{ "xwma" },					{ "xwma" } },
		{ "YOP",				"Psygnosis YOP",			{ "yop" },					{ "yop" } },
		{ "YUV4MPEG",			"YUV4MPEG pipe",			{ "yuv4mpegpipe" },			{ "y4m" } },
	};
}

std::span<const ContainerDef> StormByte::Multimedia::Tables::Container::Identity() noexcept {
	return table;
}
