function(export_ffmpeg_version)
	if(WITH_FFMPEG STREQUAL "SYSTEM")
		if(NOT AVUTIL_INCLUDE_DIRS)
			message(FATAL_ERROR "WITH_FFMPEG=SYSTEM but FindFFmpeg did not set AVUTIL_INCLUDE_DIRS")
		endif()
		list(GET AVUTIL_INCLUDE_DIRS 0 _inc)
		set(_ffv "${_inc}/libavutil/ffversion.h")
		if(NOT EXISTS "${_ffv}")
			message(FATAL_ERROR "WITH_FFMPEG=SYSTEM but ${_ffv} is missing")
		endif()
		file(STRINGS "${_ffv}" _line REGEX "^#define[ \t]+FFMPEG_VERSION[ \t]+")
		list(GET _line 0 _line)
		string(REGEX REPLACE "^#define[ \t]+FFMPEG_VERSION[ \t]+\"([^\"]+)\".*" "\\1" _ver "${_line}")
	elseif(WITH_FFMPEG STREQUAL "BUNDLED")
		set(_inc "${CMAKE_SOURCE_DIR}/thirdparty/ffmpeg/src")
		if(NOT EXISTS "${_inc}/RELEASE")
			message(FATAL_ERROR "WITH_FFMPEG=BUNDLED but ${_inc}/RELEASE is missing")
		endif()
		file(READ "${_inc}/RELEASE" _ver)
	else()
		message(FATAL_ERROR "WITH_FFMPEG must be SYSTEM or BUNDLED (got '${WITH_FFMPEG}')")
	endif()

	string(STRIP "${_ver}" _ver)
	string(REPLACE "\r" "" _ver "${_ver}")
	string(REPLACE "\n" "" _ver "${_ver}")
	string(REGEX REPLACE "^[ \t\"]+" "" _ver "${_ver}")
	string(REGEX REPLACE "[ \t\"]+$" "" _ver "${_ver}")
	string(REGEX REPLACE "^n" "" _ver "${_ver}")

	set(_maj_h "${_inc}/libavcodec/version_major.h")
	if(NOT EXISTS "${_maj_h}")
		set(_maj_h "${_inc}/libavcodec/version.h")
	endif()
	if(NOT EXISTS "${_maj_h}")
		message(FATAL_ERROR "libavcodec version header missing under ${_inc}")
	endif()
	file(STRINGS "${_maj_h}" _maj REGEX "^#define[ \t]+LIBAVCODEC_VERSION_MAJOR[ \t]+")
	list(GET _maj 0 _maj)
	string(REGEX REPLACE "^#define[ \t]+LIBAVCODEC_VERSION_MAJOR[ \t]+([0-9]+).*" "\\1" _lavc "${_maj}")
	string(STRIP "${_lavc}" _lavc)
	string(REGEX REPLACE "[^0-9]" "" _lavc "${_lavc}")

	if(_ver STREQUAL "" OR _lavc STREQUAL "")
		message(FATAL_ERROR "Could not parse FFmpeg version (ver='${_ver}' lavc='${_lavc}')")
	endif()

	string(REGEX MATCH "^([0-9]+)\\.([0-9]+)(\\.([0-9]+))?" _semver "${_ver}")
	set(_ff_maj "${CMAKE_MATCH_1}")
	set(_ff_min "${CMAKE_MATCH_2}")
	if(CMAKE_MATCH_4)
		set(_ff_pat "${CMAKE_MATCH_4}")
	else()
		set(_ff_pat "0")
	endif()
	if(_ff_maj STREQUAL "")
		message(FATAL_ERROR "FFmpeg version '${_ver}' is not MAJOR.MINOR[.PATCH]")
	endif()

	set(STORMBYTE_FFMPEG_VERSION "${_ver}" PARENT_SCOPE)
	set(STORMBYTE_FFMPEG_VERSION_MAJOR "${_ff_maj}" PARENT_SCOPE)
	set(STORMBYTE_FFMPEG_VERSION_MINOR "${_ff_min}" PARENT_SCOPE)
	set(STORMBYTE_FFMPEG_VERSION_PATCH "${_ff_pat}" PARENT_SCOPE)
	set(STORMBYTE_LIBAVCODEC_MAJOR "${_lavc}" PARENT_SCOPE)
	message(STATUS "FFmpeg ${_ver} (${_ff_maj}.${_ff_min}.${_ff_pat}, libavcodec major ${_lavc}) [${WITH_FFMPEG}]")
endfunction()

function(prepare_ffmpeg_filter_header)
	if(NOT STORMBYTE_FFMPEG_VERSION OR NOT STORMBYTE_LIBAVCODEC_MAJOR)
		message(FATAL_ERROR "prepare_ffmpeg_filter_header() needs export_ffmpeg_version() first")
	endif()
	if(NOT TARGET StormByte-Multimedia)
		message(FATAL_ERROR "prepare_ffmpeg_filter_header(): target StormByte-Multimedia does not exist yet")
	endif()

	set(_in  "${CMAKE_SOURCE_DIR}/lib/public/StormByte/multimedia/pipeline/filters/ffmpeg.hxx.in")
	set(_dir "${CMAKE_BINARY_DIR}/lib/public/StormByte/multimedia/pipeline/filters")
	set(_out "${_dir}/ffmpeg.hxx")
	if(NOT EXISTS "${_in}")
		message(FATAL_ERROR "Missing ${_in}")
	endif()

	file(MAKE_DIRECTORY "${_dir}")
	configure_file("${_in}" "${_out}" @ONLY)

	target_include_directories(StormByte-Multimedia
		SYSTEM BEFORE
		PUBLIC
			"$<BUILD_INTERFACE:${CMAKE_BINARY_DIR}/lib/public>"
	)

	include(GNUInstallDirs)
	install(FILES "${CMAKE_BINARY_DIR}/lib/public/StormByte/multimedia/pipeline/filters/ffmpeg.hxx"
		DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/StormByte/multimedia/pipeline/filters"
	)
endfunction()
