# =============================================================================
# tessdata.cmake  (#embed version)
# -----------------------------------------------------------------------------
# Generates a source file that embeds all *.traineddata files using the
# #embed preprocessor directive (C23 / C++26).
#
# Variables (set them BEFORE including this file):
#
#   TESSDATA_NAMESPACE       (required)
#       Full public namespace, e.g. "StormByte::Multimedia::Engine::OCR"
#
#   TESSDATA_FUNCTION_NAME   (optional, default = "TessData")
#       Name of the generated function
#
#   TESSDATA_DIR             (optional, default = "${CMAKE_CURRENT_LIST_DIR}/tessdata")
#       Directory containing the *.traineddata files
#
#   GENERATED_TESSDATA_FILE  (optional)
#       Full path of the generated .cxx file
#       (default = "${CMAKE_CURRENT_BINARY_DIR}/tessdata.cxx")
#
# After inclusion, the following variable is set:
#   STORMBYTE_TESSDATA_GENERATED_SOURCE
# =============================================================================

include_guard(GLOBAL)

# ----------------------------------------------------------------------
# Configuration & validation
# ----------------------------------------------------------------------
if(NOT DEFINED TESSDATA_NAMESPACE)
	message(FATAL_ERROR "[tessdata] TESSDATA_NAMESPACE must be defined before including tessdata.cmake")
endif()

if(NOT DEFINED TESSDATA_FUNCTION_NAME)
	set(TESSDATA_FUNCTION_NAME "TessData")
endif()

if(NOT DEFINED TESSDATA_DIR)
	set(TESSDATA_DIR "${CMAKE_CURRENT_LIST_DIR}/tessdata")
endif()

if(NOT DEFINED GENERATED_TESSDATA_FILE)
	set(GENERATED_TESSDATA_FILE "${CMAKE_CURRENT_BINARY_DIR}/tessdata.cxx")
endif()

# ----------------------------------------------------------------------
# Discover traineddata files
# ----------------------------------------------------------------------
file(GLOB TESSDATA_FILES CONFIGURE_DEPENDS "${TESSDATA_DIR}/*.traineddata")

if(NOT TESSDATA_FILES)
	message(WARNING "[tessdata] No .traineddata files found in \"${TESSDATA_DIR}\"")
	return()
endif()

list(LENGTH TESSDATA_FILES _count)
message(STATUS "[tessdata] Using #embed for ${_count} language(s)")
message(STATUS "[tessdata]   Namespace : ${TESSDATA_NAMESPACE}")
message(STATUS "[tessdata]   Function  : ${TESSDATA_FUNCTION_NAME}")
message(STATUS "[tessdata]   Source dir: ${TESSDATA_DIR}")

# ----------------------------------------------------------------------
# Generate declarations and switch cases
# ----------------------------------------------------------------------
set(EMBED_DECLARATIONS "")
set(SWITCH_CASES "")

foreach(file IN LISTS TESSDATA_FILES)
	get_filename_component(lang "${file}" NAME_WE)

	# Use absolute path so #embed can find the file reliably
	file(TO_CMAKE_PATH "${file}" abs_file)

	string(APPEND EMBED_DECLARATIONS
		"		constexpr std::uint8_t ${lang}_raw[] = {\n"
		"			#embed \"${abs_file}\"\n"
		"		};\n"
		"		constexpr std::span<const std::uint8_t> ${lang}_data{${lang}_raw};\n\n"
	)

	string(APPEND SWITCH_CASES
		"			case lang_id(\"${lang}\"):\n"
		"				if (lang == \"${lang}\"sv) return ${lang}_data;\n"
		"				break;\n"
	)
endforeach()

# ----------------------------------------------------------------------
# Write the generated source file
# ----------------------------------------------------------------------
set(generated_content
"// =============================================================================
// Auto-generated by tessdata.cmake (#embed version) - DO NOT EDIT MANUALLY
// Namespace : ${TESSDATA_NAMESPACE}
// Function  : ${TESSDATA_FUNCTION_NAME}
// =============================================================================

#include <StormByte/multimedia/engine/OCR/typedefs.hxx>

#include <cstdint>
#include <span>
#include <string_view>

using namespace std::string_view_literals;

namespace ${TESSDATA_NAMESPACE} {
	namespace {
${EMBED_DECLARATIONS}

		constexpr std::uint32_t lang_id(std::string_view s) noexcept {
			std::uint32_t h = 0;
			for (unsigned char c : s)
				h = h * 131u + c;
			return h;
		}

	}

	STORMBYTE_MULTIMEDIA_PUBLIC ExpectedTessData ${TESSDATA_FUNCTION_NAME}(std::string_view lang) {
		switch (lang_id(lang)) {
${SWITCH_CASES}
			default:
				break;
		}
		return Unexpected<TessDataNotFoundException>(std::string(lang));
	}
}
")

file(WRITE "${GENERATED_TESSDATA_FILE}" "${generated_content}")

# ----------------------------------------------------------------------
# Export
# ----------------------------------------------------------------------
set(STORMBYTE_TESSDATA_GENERATED_SOURCE "${GENERATED_TESSDATA_FILE}")

message(STATUS "[tessdata] Generated → ${GENERATED_TESSDATA_FILE}")