/*
 * Copyright (C) 2024-2026 David C. Manuelda (StormBytePP)
 *
 * This file is part of StormByte-Multimedia.
 *
 * StormByte-Multimedia original source is dual-licensed:
 *
 * 1. GNU Lesser General Public License v3.0 (or later)
 *    You may redistribute and/or modify this file under the terms of the
 *    GNU Lesser General Public License as published by the Free Software
 *    Foundation, either version 3 of the License, or (at your option)
 *    any later version.
 *
 * 2. Commercial license
 *    Alternatively, this file may be used under the terms of a commercial
 *    license agreement with the copyright holder
 *    (David C. Manuelda <StormByte@gmail.com>).
 *
 * Both licenses apply only to original StormByte-Multimedia source in this
 * file. Third-party components — including FFmpeg and embedded trained data —
 * remain under their own licenses and are not covered by the commercial grant.
 *
 * Neither license grants any patent rights. Any patent licenses required
 * to use this software or third-party components must be obtained separately
 * from the patent holders.
 *
 * StormByte-Multimedia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 3 along with StormByte-Multimedia. If not, see
 * <https://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * SPDX-License-Identifier: LGPL-3.0-or-later OR LicenseRef-StormByte-Commercial
 */

#include <StormByte/multimedia/media/tables/codec/table.hxx>

using namespace StormByte::Multimedia::Media::Tables::Codec;

namespace {
	constexpr CodecDef table[] = {
		{ "012V",							"Uncompressed 4:2:2 10-bit",					{ "012v" } },
		{ "4X Movie",						"4X Movie",										{ "4xm" } },
		{ "8088flex TMV",					"8088flex TMV",									{ "tmv" } },
		{ "A64 Multicolor",					"Commodore 64 multicolor",						{ "a64_multi" } },
		{ "A64 Multicolor 5",				"Commodore 64 multicolor 5",					{ "a64_multi5" } },
		{ "APNG",							"Animated PNG",									{ "apng" } },
		{ "APV",							"Advanced Professional Video",					{ "apv" } },
		{ "ASUS V1",						"ASUS V1",										{ "asv1" } },
		{ "ASUS V2",						"ASUS V2",										{ "asv2" } },
		{ "ATI VCR1",						"ATI VCR1",										{ "vcr1" } },
		{ "AV1",							"AOMedia Video 1",								{ "av1" } },
		{ "AVS",							"AVS video",									{ "avs" } },
		{ "AVS2",							"AVS2 video",									{ "avs2" } },
		{ "AVS3",							"AVS3 video",									{ "avs3" } },
		{ "AVUI",							"Avid Meridien Uncompressed",					{ "avui" } },
		{ "Alias PIX",						"Alias PIX",									{ "alias_pix" } },
		{ "Amazing Studio PAF Video",		"Amazing Studio Packed Animation File video",	{ "paf_video" } },
		{ "American Laser Games MM",		"American Laser Games MM",						{ "mmvideo" } },
		{ "AmuseGraphics Movie",			"AmuseGraphics Movie",							{ "agm" } },
		{ "ANSI Art",						"ANSI art",										{ "ansi" } },
		{ "Apple Intermediate Codec",		"Apple Intermediate Codec",						{ "aic" } },
		{ "Apple Pixlet",					"Apple Pixlet",									{ "pixlet" } },
		{ "Argonaut Games Video",			"Argonaut Games Video",							{ "argo" } },
		{ "Auravision Aura",				"Auravision Aura",								{ "aura" } },
		{ "Auravision Aura 2",				"Auravision Aura 2",							{ "aura2" } },
		{ "Avid AVI Codec",					"Avid AVI Codec",								{ "avrn" } },
		{ "Avid Meridien",					"Avid 1:1 10-bit RGB Packer",					{ "avrp" } },
		{ "BMP",							"Windows Bitmap",								{ "bmp" } },
		{ "BRender PIX",					"BRender PIX",									{ "brender_pix" } },
		{ "Beam Software VB",				"Beam Software VB",								{ "vb" } },
		{ "Bethesda VID",					"Bethesda VID",									{ "bethsoftvid" } },
		{ "Bink Video",						"RAD Bink video",								{ "binkvideo" } },
		{ "Bitmap Brothers JV",				"Bitmap Brothers JV",							{ "jv" } },
		{ "Bitpacked",						"Bitpacked",									{ "bitpacked" } },
		{ "Brooktree ProSumer",				"Brooktree ProSumer",							{ "prosumer" } },
		{ "Brute Force and Ignorance",		"Brute Force & Ignorance",						{ "bfi" } },
		{ "CD Graphics",					"CD Graphics",									{ "cdgraphics" } },
		{ "CDToons",						"Sprint Bitmask",								{ "cdtoons" } },
		{ "CPiA",							"CPiA video",									{ "cpia" } },
		{ "CamStudio",						"CamStudio",									{ "cscd" } },
		{ "Canopus HQ",						"Canopus HQ / HQA",								{ "hq_hqa" } },
		{ "Canopus HQX",					"Canopus HQX",									{ "hqx" } },
		{ "Canopus Lossless",				"Canopus Lossless",								{ "cllc" } },
		{ "Chinese AVS",					"Chinese AVS (CAVS)",							{ "cavs" } },
		{ "Chronomaster DFA",				"Chronomaster DFA",								{ "dfa" } },
		{ "CineForm HD",					"GoPro CineForm",								{ "cfhd" } },
		{ "Cinepak",						"Cinepak",										{ "cinepak" } },
		{ "Cintel RAW",						"Cintel RAW",									{ "cri" } },
		{ "Cirrus Logic AccuPak",			"Cirrus Logic AccuPak",							{ "cljr" } },
		{ "ClearVideo",						"Iterated Systems ClearVideo",					{ "clearvideo" } },
		{ "Commodore CDXL",					"Commodore CDXL",								{ "cdxl" } },
		{ "Creative YUV",					"Creative YUV",									{ "cyuv" } },
		{ "DNxHD",							"Avid DNxHD / DNxHR",							{ "dnxhd" } },
		{ "DNxUncompressed",				"Avid DNxUncompressed",							{ "dnxuc" } },
		{ "DPX",							"SMPTE DPX",									{ "dpx" } },
		{ "DV Video",						"IEC 61834 / SMPTE 314M",						{ "dvvideo" } },
		{ "Daala",							"Xiph Daala",									{ "daala" } },
		{ "Delphine CIN Video",				"Delphine Software CIN video",					{ "dsicinvideo" } },
		{ "Deluxe Paint Animation",			"Deluxe Paint Animation",						{ "anm" } },
		{ "Digital Pictures SGA",			"Digital Pictures SGA",							{ "sga" } },
		{ "Dirac",							"BBC Dirac",									{ "dirac" } },
		{ "DirectDraw Surface",				"DDS",											{ "dds" } },
		{ "Discworld II BMV Video",			"Discworld II BMV video",						{ "bmv_video" } },
		{ "Duck TrueMotion 1",				"Duck TrueMotion 1",							{ "truemotion1" } },
		{ "Duck TrueMotion 2",				"Duck TrueMotion 2",							{ "truemotion2" } },
		{ "Duck TrueMotion 2RT",			"Duck TrueMotion 2 RT",							{ "truemotion2rt" } },
		{ "Dxtory",							"Dxtory",										{ "dxtory" } },
		{ "EVC",							"Essential Video Coding (MPEG-5)",				{ "evc" } },
		{ "Electronic Arts CMV",			"Electronic Arts CMV",							{ "eacmv" } },
		{ "Electronic Arts MAD",			"Electronic Arts MAD",							{ "eamad" } },
		{ "Electronic Arts TGQ",			"Electronic Arts TGQ",							{ "eatgq" } },
		{ "Electronic Arts TGV",			"Electronic Arts TGV",							{ "eatgv" } },
		{ "Electronic Arts TQI",			"Electronic Arts TQI",							{ "eatqi" } },
		{ "Escape 124",						"Escape 124",									{ "escape124" } },
		{ "Escape 130",						"Escape 130",									{ "escape130" } },
		{ "FFV1",							"FFmpeg lossless video",						{ "ffv1" } },
		{ "FFVHuff",						"FFmpeg HuffYUV",								{ "ffvhuff" } },
		{ "FITS",							"Flexible Image Transport System",				{ "fits" } },
		{ "FLIC",							"Autodesk FLI/FLC",								{ "flic" } },
		{ "FM Screen Capture",				"FM Screen Capture",							{ "fmvc" } },
		{ "Feeble DXA",						"Feeble Files DXA",								{ "dxa" } },
		{ "Flash Screen Video",				"Flash Screen Video v1",						{ "flashsv" } },
		{ "Flash Screen Video 2",			"Flash Screen Video v2",						{ "flashsv2" } },
		{ "Forward Uncompressed",			"Forward Uncompressed",							{ "frwu" } },
		{ "Fraps",							"Fraps",										{ "fraps" } },
		{ "GEM Raster",						"GEM Raster",									{ "gem" } },
		{ "GIF",							"Graphics Interchange Format",					{ "gif" } },
		{ "Go2Meeting",						"Go2Meeting",									{ "g2m" } },
		{ "Gremlin Digital Video",			"Gremlin Digital Video",						{ "gdv" } },
		{ "Gryphn ARBC",					"Gryphn ARBC",									{ "arbc" } },
		{ "H.261",							"ITU H.261",									{ "h261" } },
		{ "H.263",							"ITU H.263",									{ "h263" } },
		{ "H.263+",							"H.263+",										{ "h263p" } },
		{ "H.264",							"Advanced Video Coding",						{ "h264", "avc" } },
		{ "H.265",							"High Efficiency Video Coding",					{ "hevc", "h265" } },
		{ "H.266",							"Versatile Video Coding",						{ "vvc", "h266" } },
		{ "HAP",							"Vidvox Hap",									{ "hap" } },
		{ "HNM4 Video",						"Cryo HNM4 video",								{ "hnm4video" } },
		{ "HuffYUV",						"HuffYUV",										{ "huffyuv" } },
		{ "HymT",							"Hymson HYMT",									{ "hymt" } },
		{ "IBM UltiMotion",					"IBM UltiMotion",								{ "ulti" } },
		{ "IFF ILBM",						"IFF ILBM",										{ "iff_ilbm", "iff_byterun1" } },
		{ "IPU",							"Sony PS2 IPU",									{ "ipu" } },
		{ "Indeo 2",						"Intel Indeo 2",								{ "indeo2" } },
		{ "Indeo 3",						"Intel Indeo 3",								{ "indeo3" } },
		{ "Indeo 4",						"Intel Indeo 4",								{ "indeo4" } },
		{ "Indeo 5",						"Intel Indeo 5",								{ "indeo5" } },
		{ "Infinity IMM4",					"Infinity IMM4",								{ "imm4" } },
		{ "Infinity IMM5",					"Infinity IMM5",								{ "imm5" } },
		{ "Intel H.263",					"Intel H.263",									{ "h263i" } },
		{ "Interplay C93",					"Interplay C93",								{ "c93" } },
		{ "Interplay Video",				"Interplay MVE video",							{ "interplayvideo" } },
		{ "JPEG 2000",						"JPEG 2000",									{ "jpeg2000" } },
		{ "JPEG XL",						"JPEG XL",										{ "jpegxl" } },
		{ "JPEG XL Animated",				"JPEG XL animation",							{ "jpegxl_anim" } },
		{ "JPEG XS",						"JPEG XS",										{ "jpegxs" } },
		{ "JPEG-LS",						"JPEG-LS",										{ "jpegls" } },
		{ "Karl Morton Video",				"Karl Morton's Video",							{ "kmvc" } },
		{ "Kega Game Video",				"Kega Game Video",								{ "kgv1" } },
		{ "LEAD MCMP",						"LEAD MCMP",									{ "lead" } },
		{ "LEAD Screen Capture",			"LEAD Screen Capture",							{ "lscr" } },
		{ "LOCO",							"LOCO lossless",								{ "loco" } },
		{ "Lagarith",						"Lagarith lossless",							{ "lagarith" } },
		{ "Lossless JPEG",					"Lossless JPEG",								{ "ljpeg" } },
		{ "LucasArts SANM",					"LucasArts Smush v2",							{ "sanm" } },
		{ "MJPEG",							"Motion JPEG",									{ "mjpeg" } },
		{ "MJPEGB",							"Motion JPEG-B",								{ "mjpegb" } },
		{ "MPEG-1 Video",					"MPEG-1 video",									{ "mpeg1video" } },
		{ "MPEG-2 Video",					"MPEG-2 video",									{ "mpeg2video" } },
		{ "MPEG-4 Part 2",					"MPEG-4 Part 2",								{ "mpeg4" } },
		{ "MS ATC Screen",					"MS ATC Screen",								{ "msa1" } },
		{ "MS Compressed Canvas",			"MS Compressed Canvas 9",						{ "mscc" } },
		{ "MS Expression Encoder Screen",	"MS Expression Encoder Screen",					{ "mts2" } },
		{ "MS MPEG-4 v1",					"Microsoft MPEG-4 v1",							{ "msmpeg4v1" } },
		{ "MS MPEG-4 v2",					"Microsoft MPEG-4 v2",							{ "msmpeg4v2" } },
		{ "MS MPEG-4 v3",					"Microsoft MPEG-4 v3",							{ "msmpeg4v3" } },
		{ "MS Screen 1",					"Windows Media Screen 1",						{ "mss1" } },
		{ "MS Screen 2",					"Windows Media Screen 2",						{ "mss2" } },
		{ "MSZH",							"Avalon MSZH",									{ "mszh" } },
		{ "MagicYUV",						"MagicYUV",										{ "magicyuv" } },
		{ "MatchWare Screen Capture",		"MatchWare Screen Capture",						{ "mwsc" } },
		{ "Matrox Uncompressed",			"Matrox Uncompressed M-JPEG",					{ "m101" } },
		{ "Media 100",						"Media 100",									{ "media100" } },
		{ "Microsoft Paint",				"Microsoft Paint",								{ "msp2" } },
		{ "Microsoft RLE",					"Microsoft RLE",								{ "msrle" } },
		{ "Microsoft Video 1",				"Microsoft Video 1",							{ "msvideo1" } },
		{ "MidiVid 3.0",					"MidiVid 3.0",									{ "mv30" } },
		{ "MidiVid Archive",				"MidiVid Archive",								{ "mvha" } },
		{ "MidiVid VQ",						"MidiVid VQ",									{ "mvdv" } },
		{ "Mimic",							"Mimic",										{ "mimic" } },
		{ "Miro VideoXL",					"Miro VideoXL",									{ "vixl" } },
		{ "MobiClip",						"ACT-L3 / MobiClip",							{ "mobiclip" } },
		{ "Motion Pixels",					"Motion Pixels",								{ "motionpixels" } },
		{ "MxPEG",							"Mobotix MxPEG",								{ "mxpeg" } },
		{ "NewTek SpeedHQ",					"NewTek SpeedHQ",								{ "speedhq" } },
		{ "Nintendo THP",					"Nintendo THP",									{ "thp" } },
		{ "NotchLC",						"NotchLC",										{ "notchlc" } },
		{ "NuppelVideo",					"NuppelVideo / RTJPEG",							{ "nuv" } },
		{ "OpenEXR",						"OpenEXR",										{ "exr" } },
		{ "PAM",							"Portable Arbitrary Map",						{ "pam" } },
		{ "PBM",							"Portable Bitmap",								{ "pbm" } },
		{ "PCX",							"PC Paintbrush",								{ "pcx" } },
		{ "PFM",							"Portable FloatMap",							{ "pfm" } },
		{ "PGM",							"Portable Graymap",								{ "pgm" } },
		{ "PGMYUV",							"Portable Graymap YUV",							{ "pgmyuv" } },
		{ "PGX",							"JPEG 2000 PGX",								{ "pgx" } },
		{ "PHM",							"Portable Half FloatMap",						{ "phm" } },
		{ "PNG",							"Portable Network Graphics",					{ "png" } },
		{ "PPM",							"Portable Pixmap",								{ "ppm" } },
		{ "Photo CD",						"Kodak Photo CD",								{ "photocd" } },
		{ "Photoshop PSD",					"Adobe Photoshop",								{ "psd" } },
		{ "Pictor",							"Pictor / PC Paint",							{ "pictor" } },
		{ "PlayDate Video",					"PlayDate Video",								{ "pdv" } },
		{ "PlayStation MDEC",				"Sony PlayStation MDEC",						{ "mdec" } },
		{ "ProRes",							"Apple ProRes",									{ "prores" } },
		{ "ProRes RAW",						"Apple ProRes RAW",								{ "prores_raw" } },
		{ "Psygnosis YOP",					"Psygnosis YOP",								{ "yop" } },
		{ "Q-Team QPEG",					"Q-Team QPEG",									{ "qpeg" } },
		{ "QOI",							"Quite OK Image",								{ "qoi" } },
		{ "QuickDraw",						"Apple QuickDraw",								{ "qdraw" } },
		{ "QuickTime 8BPS",					"Planar RGB (8BPS)",							{ "8bps" } },
		{ "QuickTime Animation",			"Apple Animation (RLE)",						{ "qtrle" } },
		{ "QuickTime RPZA",					"Apple Road Pizza",								{ "rpza" } },
		{ "QuickTime SMC",					"Apple Graphics (SMC)",							{ "smc" } },
		{ "R10K",							"Uncompressed RGB 10-bit (R10K)",				{ "r10k" } },
		{ "R210",							"Uncompressed RGB 10-bit",						{ "r210" } },
		{ "RL2",							"RL2 video",									{ "rl2" } },
		{ "RTV1",							"RTV1",											{ "rtv1" } },
		{ "Radiance HDR",					"Radiance RGBE",								{ "radiance_hdr" } },
		{ "RealVideo 1.0",					"RealVideo 1.0",								{ "rv10" } },
		{ "RealVideo 2.0",					"RealVideo 2.0",								{ "rv20" } },
		{ "RealVideo 3.0",					"RealVideo 3.0",								{ "rv30" } },
		{ "RealVideo 4.0",					"RealVideo 4.0",								{ "rv40" } },
		{ "RealVideo 6.0",					"RealVideo 6.0",								{ "rv60" } },
		{ "RemotelyAnywhere",				"RemotelyAnywhere Screen Capture",				{ "rasc" } },
		{ "Renderware TXD",					"Renderware TXD",								{ "txd" } },
		{ "Resolume DXV",					"Resolume DXV",									{ "dxv" } },
		{ "RoQ Video",						"Id RoQ video",									{ "roq" } },
		{ "SGI",							"Silicon Graphics image",						{ "sgi" } },
		{ "SGI RLE",						"Silicon Graphics RLE",							{ "sgirle" } },
		{ "SMV JPEG",						"Sigmatel Motion Video",						{ "smvjpeg" } },
		{ "SVG",							"Scalable Vector Graphics",						{ "svg" } },
		{ "Screen Recorder Gold",			"Screen Recorder Gold",							{ "srgc" } },
		{ "ScreenPressor",					"ScreenPressor",								{ "scpr" } },
		{ "Screenpresso",					"Screenpresso",									{ "screenpresso" } },
		{ "SheerVideo",						"BitJazz SheerVideo",							{ "sheervideo" } },
		{ "Sierra VMD Video",				"Sierra VMD video",								{ "vmdvideo" } },
		{ "Silicon Graphics MVC1",			"SGI MVC1",										{ "mvc1" } },
		{ "Silicon Graphics MVC2",			"SGI MVC2",										{ "mvc2" } },
		{ "Simbiosis IMX",					"Simbiosis IMX",								{ "simbiosis_imx" } },
		{ "Smacker Video",					"RAD Smacker video",							{ "smackvid" } },
		{ "Snow",							"FFmpeg Snow",									{ "snow" } },
		{ "Sorenson Spark",					"Flash Video (H.263)",							{ "flv1" } },
		{ "Sorenson Video 1",				"Sorenson Video 1",								{ "svq1" } },
		{ "Sorenson Video 3",				"Sorenson Video 3",								{ "svq3" } },
		{ "Sun Raster",						"Sun Rasterfile",								{ "sunrast" } },
		{ "Sunplus JPEG",					"Sunplus MJPEG",								{ "sp5x" } },
		{ "TDSC",							"TDSC",											{ "tdsc" } },
		{ "TIFF",							"Tagged Image File Format",						{ "tiff" } },
		{ "Targa",							"Truevision TGA",								{ "targa" } },
		{ "Targa Y216",						"Truevision TGA Y216",							{ "targa_y216" } },
		{ "TechSmith Camtasia",				"TechSmith Screen Capture",						{ "tscc" } },
		{ "TechSmith Camtasia 2",			"TechSmith Screen Capture 2",					{ "tscc2" } },
		{ "Theora",							"Xiph Theora",									{ "theora" } },
		{ "Tiertex SEQ",					"Tiertex Limited SEQ",							{ "tiertexseqvideo" } },
		{ "Ut Video",						"Ut Video",										{ "utvideo" } },
		{ "V.Flash PTX",					"V.Flash PTX",									{ "ptx" } },
		{ "V210",							"Uncompressed 4:2:2 10-bit",					{ "v210" } },
		{ "V210X",							"Uncompressed 4:2:2 10-bit (V210X)",			{ "v210x" } },
		{ "VBLE",							"VBLE lossless",								{ "vble" } },
		{ "VC-1",							"SMPTE VC-1",									{ "vc1" } },
		{ "VC-1 Image",						"SMPTE VC-1 Image",								{ "vc1image" } },
		{ "VMware Screen",					"VMware Screen Codec",							{ "vmnc" } },
		{ "VP3",							"On2 VP3",										{ "vp3" } },
		{ "VP4",							"On2 VP4",										{ "vp4" } },
		{ "VP5",							"On2 VP5",										{ "vp5" } },
		{ "VP6",							"On2 VP6",										{ "vp6" } },
		{ "VP6A",							"On2 VP6 Alpha",								{ "vp6a" } },
		{ "VP6F",							"On2 VP6 Flash",								{ "vp6f" } },
		{ "VP7",							"On2 VP7",										{ "vp7" } },
		{ "VP8",							"On2 / Google VP8",								{ "vp8" } },
		{ "VP9",							"Google VP9",									{ "vp9" } },
		{ "ViewQuest VQC",					"ViewQuest VQC",								{ "vqc" } },
		{ "Vizrt Binary",					"Vizrt Binary Image",							{ "vbn" } },
		{ "WBMP",							"Wireless Bitmap",								{ "wbmp" } },
		{ "WMV 7",							"Windows Media Video 7",						{ "wmv1" } },
		{ "WMV 8",							"Windows Media Video 8",						{ "wmv2" } },
		{ "WMV 9",							"Windows Media Video 9",						{ "wmv3" } },
		{ "WMV 9 Image",					"Windows Media Video 9 Image",					{ "wmv3image" } },
		{ "WebP",							"WebP",											{ "webp" } },
		{ "WebP Animated",					"Animated WebP",								{ "webp_anim" } },
		{ "Westwood VQA",					"Westwood VQA",									{ "ws_vqa" } },
		{ "WinCAM",							"WinCAM Motion Video",							{ "wcmv" } },
		{ "Wing Commander III",				"Wing Commander III video",						{ "xan_wc3" } },
		{ "Wing Commander IV",				"Wing Commander IV video",						{ "xan_wc4" } },
		{ "Winnov WNV1",					"Winnov WNV1",									{ "wnv1" } },
		{ "X-Face",							"X-Face",										{ "xface" } },
		{ "XBM",							"X BitMap",										{ "xbm" } },
		{ "XPM",							"X PixMap",										{ "xpm" } },
		{ "XWD",							"X Window Dump",								{ "xwd" } },
		{ "Y41P",							"Uncompressed YUV 4:1:1 12-bit",				{ "y41p" } },
		{ "YUV4",							"Uncompressed packed 4:2:0",					{ "yuv4" } },
		{ "YUYON Loco",						"YUYON Loco",									{ "ylc" } },
		{ "ZLIB Video",						"Lossless zlib video",							{ "zlib" } },
		{ "ZeroCodec",						"ZeroCodec lossless",							{ "zerocodec" } },
		{ "Zip Motion Blocks Video",		"Zip Motion Blocks Video",						{ "zmbv" } },
		{ "id Cinematic",					"id Quake II cinematic",						{ "idcin" } },
		{ "innoHeim RSCC",					"innoHeim/Rsupport Screen Capture",				{ "rscc" } },
		{ "vMix",							"vMix Uncompressed",							{ "vmix" } },
	};
}

std::span<const CodecDef> StormByte::Multimedia::Media::Tables::Codec::Video() noexcept {
	return table;
}
